### ISSUE TITLE
Добавить описание проекта и состав команды

### ISSUE THREAD

**Issue by sevryukov** [robot-lab/judyst-link-analysis#25]

**Comment by Rexarrior** [comment]
Выполнение задерживается, т.к. планируется разделение репозитория на два, в соответствии со структурой проекта. Страница с составом команды создана на [вики](https://github.com/Rexarrior/ALT/wiki/Состав-команды)

**Comment by Rexarrior** [comment]
Описание добавлено на [вики](https://github.com/robot-lab/judyst-main-web-service/wiki) главного репозитория проекта, вместе с полным списком участников.
