### ISSUE TITLE
Нулевые файлы в краулере

### ISSUE THREAD

**Issue by Rexarrior** [robot-lab/judyst-link-analysis#28]
По результатам анализа всей базы: 
Три txt-файла из 30 тыс. оказались нулевой длины. Проверено вручную, текст выдрался нормально. Кроме того, оказалось, что некоторые pdf файлы не были загружены вообще.

Итого:
добавить в web_crawler.load_resolution_texts() проверки:

1. скачался ли pdf
2. если нет, доступен ли сайт ksrf
3. если скачался, то выдрался ли из него текст в txt

**Comment by mehwhatever0** [comment]
Закрыто в связи с переносом компоненты web_crawler в другой репозиторий. [Ссылка на issue](https://github.com/robot-lab/judyst-web-crawler/issues/4)
