### ISSUE TITLE
Баг с аргументом docTypes

### ISSUE THREAD

**Issue by Drokonor** [robot-lab/judyst-link-analysis#83]
Неправильно инициализируется аргумент docTypes в классе HeadersFilter() в models.py

Фрагмент кода, вызвавший ошибку:

if hasattr(docTypes, '__iter__'):
            self.doc_types = set(docTypes)
        else:
            self.doc_types = set()

**Comment by mehwhatever0** [comment]
Было решено ранее.  Видимо, тестировалась старая версия кода.
