### ISSUE TITLE
Тестирование грубого анализа

### ISSUE THREAD

**Issue by Drokonor** [robot-lab/judyst-link-analysis#90]
Нужно написать несколько тестов для грубой выборки, попробовать максимальное количество разных уникальных грубых ссылок и контекста рядом с ними.

**Comment by Drokonor** [comment]
Было создано несколько тестов для грубого анализа, после их работы была найдена проблема - в предложениях начинающихся на цифру грубые ссылки с помощью функции get_rough_links в rough_analysis.py не выявляются.

**Comment by Drokonor** [comment]
Проблема была решена, тестирование прошло.

**Comment by mehwhatever0** [comment]
Поддержка латиницы добавлена. Добавление цифр не планируется.
